import requests
import json
from typing import Dict, Any
from config import Config

class OpenRouterClient:
    def __init__(self, api_key: str = None):
        self.api_key = api_key or Config.OPENROUTER_API_KEY
        self.api_url = Config.OPENROUTER_API_URL
        self.headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "HTTP-Referer": "http://localhost:8000",
            "X-Title": "Figma MCP Server"
        }
    
    def analyze_design(self, component_info: Dict[str, Any]) -> str:
        """Analyze design using OpenRouter AI"""
        
        # Create a more detailed prompt
        prompt = f"""As a UI/UX design expert, analyze this Figma component:

Component Name: {component_info.get('name', 'Unknown')}
Component Type: {component_info.get('type', 'Unknown')}

Description: {component_info.get('description', 'No description provided')}

Structure: This component contains {len(component_info.get('children', []))} child elements.

Please provide a comprehensive design analysis covering:
1. Design patterns and visual hierarchy
2. Usability and user experience
3. Accessibility considerations
4. Potential improvements
5. Best practices for implementation

Format your response in clear sections with bullet points."""
        
        payload = {
            "model": "openai/gpt-3.5-turbo",
            "messages": [
                {
                    "role": "system",
                    "content": "You are a UI/UX design expert. Provide detailed, constructive analysis of design components."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            "temperature": 0.7,
            "max_tokens": 1000
        }
        
        try:
            print(f"Sending request to OpenRouter with model: {payload['model']}")
            response = requests.post(self.api_url, headers=self.headers, json=payload)
            
            if response.status_code == 200:
                result = response.json()
                return result["choices"][0]["message"]["content"]
            else:
                error_msg = f"OpenRouter Error ({response.status_code}): {response.text}"
                print(error_msg)
                return f"Error analyzing design: {error_msg}"
                
        except Exception as e:
            error_msg = f"Exception in OpenRouter call: {str(e)}"
            print(error_msg)
            return error_msg
    
    def generate_markdown_content(self, component_info: Dict[str, Any], analysis: str) -> str:
        """Generate markdown content from analysis"""
        
        # If analysis is an error message, create a simple markdown
        if analysis.startswith("Error"):
            return f"""# Design Analysis for {component_info.get('name', 'Component')}

## Component Information
- **Name:** {component_info.get('name', 'Unknown')}
- **Type:** {component_info.get('type', 'Unknown')}
- **ID:** {component_info.get('id', 'Unknown')}

## Analysis Status
⚠️ **Analysis could not be completed**

{analysis}

## What to Check
1. Verify your OpenRouter API key is correct
2. Ensure you have sufficient credits
3. Check your internet connection
4. Try again later

---
*Generated by Figma MCP Server*
"""
        
        # Create a structured markdown document
        markdown = f"""# Design Analysis: {component_info.get('name', 'Component')}

## Overview
- **Type:** {component_info.get('type', 'Unknown')}
- **Component ID:** {component_info.get('id', 'Unknown')}
- **Image:** ![Component]({component_info.get('image_url', '')})

## Description
{component_info.get('description', 'No description provided.')}

## Structure
This component contains {len(component_info.get('children', []))} child elements:
"""
        
        # Add children if any
        for i, child in enumerate(component_info.get('children', [])[:5]):
            markdown += f"- {child.get('type', 'Element')}: {child.get('name', 'Unnamed')}\n"
        
        if len(component_info.get('children', [])) > 5:
            markdown += f"- ... and {len(component_info.get('children', [])) - 5} more elements\n"
        
        markdown += f"""
## Design Analysis
{analysis}

## Recommendations
1. **Accessibility:** Ensure proper contrast ratios and ARIA labels
2. **Responsiveness:** Test on different screen sizes
3. **Consistency:** Maintain consistent spacing and styling
4. **Performance:** Optimize any images or complex elements

---
*Generated by Figma MCP Server on demand*
"""
        
        return markdown
    
    # ⚠️ CRITICAL: This method MUST be indented exactly 4 spaces from the class
    def analyze_with_prompt(self, custom_prompt: str) -> str:
        """Analyze with a custom prompt"""
        
        payload = {
            "model": "openai/gpt-3.5-turbo",
            "messages": [
                {
                    "role": "system",
                    "content": "You are a technical planning expert. Generate detailed implementation plans."
                },
                {
                    "role": "user",
                    "content": custom_prompt
                }
            ],
            "temperature": 0.7,
            "max_tokens": 2000
        }
        
        try:
            response = requests.post(self.api_url, headers=self.headers, json=payload)
            response.raise_for_status()
            result = response.json()
            return result["choices"][0]["message"]["content"]
        except Exception as e:
            return f"Error generating plan: {str(e)}"